### ISSUE TITLE
babel-idempotent issue

### ISSUE THREAD

**Issue by alechp** [servexyz/npm-starter-sample-module#1]
noticed this throws dependency issue when trying to use this in a project without babel-idempotent present

### Error log
```
> prisma-starter@ test /Users/alechp/Code/servexyz/starter/.repositories/prisma-starter/src
> ava


internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'idempotent-babel-polyfill'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/alechp/Code/servexyz/starter/.repositories/prisma-starter/src/node_modules/npm-starter-sample-module/build/webpack:/external "idempotent-babel-polyfill":1:1)
    at n (/Users/alechp/Code/servexyz/starter/.repositories/prisma-starter/src/node_modules/npm-starter-sample-module/build/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/Users/alechp/Code/servexyz/starter/.repositories/prisma-starter/src/node_modules/npm-starter-sample-module/build/webpack:/external "idempotent-babel-polyfill":1:1)
    at n (/Users/alechp/Code/servexyz/starter/.repositories/prisma-starter/src/node_modules/npm-starter-sample-module/build/webpack:/webpack/bootstrap:19:1)
    at /Users/alechp/Code/servexyz/starter/.repositories/prisma-starter/src/node_modules/npm-starter-sample-module/build/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/Users/alechp/Code/servexyz/starter/.repositories/prisma-starter/src/node_modules/npm-starter-sample-module/build/webpack:/webpack/bootstrap:83:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at extensions.(anonymous function) (/Users/alechp/Code/servexyz/starter/.repositories/prisma-starter/src/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/alechp/Code/servexyz/starter/.repositories/prisma-starter/src/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
  ✖ service/tests/foo.test.js exited with a non-zero exit code: 1

  0 tests passed
  1 uncaught exception
```

**Comment by alechp** [comment]
fixed
